import sys
import pygame
import pygame.gfxdraw
from pygame.constants import QUIT
from src.bowyer_watson import BowyerWatson
from src.room_generation import generate_rooms




class Demo():
    """
    Class creates three different room sets and triangulations for
    each of the sets.
    Then demonstrates the way a set is generated by drawing
    generated squares and triangles with pygame.
    """
    def __init__(self,width:int,height:int,tile_size:int):
        """Class constructor for Demo class

        Args:
            width (int): Width of screen to draw on.
            height (int): Height of screen to draw on.
            tile_size (int): Tile size used for room size.
        """
        pygame.init()
        self.width = width
        self.height = height

        self.room_and_centers1 = generate_rooms(20,width,height,32)
        self.bowyer_watson1 = BowyerWatson(self.room_and_centers1[1],width,height)
        self.bowyer_watson1.run()

        self.room_and_centers2 = generate_rooms(200,width,height,tile_size)
        self.bowyer_watson2 = BowyerWatson(self.room_and_centers2[1],width,height)
        self.bowyer_watson2.run()

        self.room_and_centers3 = generate_rooms(2000,width,height,tile_size)
        self.bowyer_watson3 = BowyerWatson(self.room_and_centers3[1],width,height)
        self.bowyer_watson3.run()
        self.screen = pygame.display.set_mode((self.width,self.height))

    def run(self):
        """Run method calls drawing functions.
        """
        background = pygame.Surface((self.width,self.height))
        background.fill('black')
        clock = pygame.time.Clock()
        self.timer = 0

        while True:
            for event in pygame.event.get():
                if event.type == QUIT:
                    print("bye bye")
                    pygame.quit()
                    sys.exit()
            self.screen.blit(background,(0,0))
            if self.timer < 15:
                self.draw_demo1()
            elif self.timer < 30:
                self.draw_demo2()
            else:
                self.draw_demo3()
            self.timer += 1/60
            clock.tick(60)
            pygame.display.flip()

    def draw_demo1(self):
        """Draw first demo on the screen.
        """
        if self.timer < 15:
            for room in self.room_and_centers1[0]:
                room.draw(self.screen,'blue')
            if self.timer >= 5:
                for triangle in self.bowyer_watson1.triangulation:
                    if self.timer >= 10:
                        triangle.draw(self.screen,'red', 1)
                    else:
                        triangle.draw(self.screen,'red',0)

    def draw_demo2(self):
        """Draw second demo on the screen.
        """
        for room in self.room_and_centers2[0]:
            room.draw(self.screen,'blue')

        if self.timer>=20:
            for triangle in self.bowyer_watson2.triangulation:
                triangle.draw(self.screen,'red',0)

    def draw_demo3(self):
        """Draw third demo on the screen.
        """
        for room in self.room_and_centers3[0]:
            room.draw(self.screen,'blue')
        if self.timer >= 35:
            for triangle in self.bowyer_watson3.triangulation:
                triangle.draw(self.screen,'red',0)
